### ISSUE TITLE
"schedule" command not creating any schedules, returns textual error response instead

### ISSUE THREAD

**Issue by jonnysandu** [brianpgerson/the-count#11]
I wanted to primarily use callie for the schedule command, but after following your exact syntax over many tests, I still couldn't get "schedule" to successfully work. Using the `start date` command however did work correctly, for example something like `start date: 2018-04-03, event: cool`

I apologize for how weak the detail in this issue is going to be, i'm creating this about a week after this happened.

**Command used:**
`@callie schedule: weekly, day: sunday, event: cool`

**Response error:**
Returned an error that I didn't remember exactly off the top of my head, but I believe it was this one: (combed through your code looking for familiar errors)
`Couldn't find a countdown for that event...sorry. Try asking me for "list" to see your current countdowns!`
I can't say I'm 100% this was it /shrug

_/edit If you'd like me to reinstall callie and track down details like a proper developer, let me know :) I'm willing to put in the time to get this app to work for me since it's exactly what I need and there's really nothing else like it out there right now that's lightweight and quick._

**Comment by brianpgerson** [comment]
Thanks man! I will take a look today (probably later this evening) and see what I can do!

**Comment by brianpgerson** [comment]
that said, if you get bored and want somethin to do...feel free to take a look!

**Comment by brianpgerson** [comment]
I never responded to this - I am sorry! This was resolved...we were temporarily pointing at the test DB instead of production due to a config issue. That was fixed later that same day. Hopefully you noticed!

Closing this for now.

**Comment by socialboards-christian** [comment]
Hi Brian! Thanks for a great app :)

I think this bug is back:

Christian [11:46]
@callie schedule: weekly, day: sunday, event: cool
callie APP [11:46]
If you'd like to pick a day of the week, please set it like `day: monday`, for example
Couldn't find a countdown for that event...sorry. Try asking me for "list" to see your current countdowns!

And this is probably the same bug:
Christian [10:53]
@callie schedule: daily, event: Lunch time (edited) 

callie APP [10:53]
Couldn't find a countdown for that event...sorry. Try asking me for "list" to see your current countdowns!


Best regards,
Christian

**Comment by brianpgerson** [comment]
hmmm... i'm trying this feature out right now and it appears to be working fine? are you sure those event names are correct?
